# Generated by Django 3.2.3 on 2023-11-23 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_auto_20231117_2020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('from_user', 'to_user')},
        ),
    ]
