version: '3'


volumes:
  static:
  media:
  pg_data:


services:
  db:
    image: postgres:13
    # env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: bobts/kittybook_backend
    volumes:
      - static:/backend_static
      # - media:/media
      - media:/app/media

  nginx:
    image: nginx:1.19.3
    depends_on:
      - frontend
      - backend
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/app/media
      # - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/

  frontend:
    # build: ./frontend
    image: bobts/kittybook_frontend
    ports:
      - '3000:3000'