# Generated by Django 3.2.3 on 2023-11-16 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя котика')),
                ('birthday', models.DateTimeField(verbose_name='Дата рождения')),
                ('color', models.CharField(max_length=16, verbose_name='Окрас')),
                ('breed', models.CharField(max_length=32, verbose_name='Порода')),
                ('history', models.TextField(verbose_name='История о котике')),
                ('image', models.ImageField(default=None, null=True, upload_to='cats/images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
