# Generated by Django 3.2.3 on 2023-11-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitty',
            name='birthday',
        ),
        migrations.AddField(
            model_name='kitty',
            name='birth_year',
            field=models.IntegerField(default=2000, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
