# Generated by Django 3.2.3 on 2023-11-23 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitty', '0002_auto_20231117_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitty',
            name='birth_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1985, message='Врятли котики столько живут,если это правда - то обратитесь в книгу рекордов Гиннеса!'), django.core.validators.MaxValueValidator(2023, message='Возраст не может быть меньше 0')], verbose_name='Дата рождения'),
        ),
    ]
